# --- Qatten specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
#epsilon_anneal_time: 200000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "qplex_curiosity_vdn_learner_ca"
double_q: True
mixer: "dmaq_qatten"
mixing_embed_dim: 32
hypernet_embed: 64
adv_hypernet_layers: 1
adv_hypernet_embed: 64

num_kernel: 4
is_minus_one: True
is_adv_attention: True
is_stop_gradient: True

#.. added for EMU ---------------------------------

#.. hypers-parameter
ec_buffer_stats_update_interval   : 200    # 200
ec_buffer_embedder_update_interval: 10000  # 10000
emb_training_batch                : 102400 # 102400 (10% sample)
emb_training_mini_batch           : 1024
t_EC_update                       : 0
buffer_size_update                : 5000 # shuold be smaller than buffer_size

rtol_memory  : 0.0      
atol_memory  : 0.0013 

#.. control variables
memory_emb_type     : 3      # memory construction based on - 1: x_dim + random projection, 2: state (global) + embedding function, 3: state (global) + embedding with reconstruuction loss
emb_out_type        : 3      # 1: FC, 2: tanh, 3: LayerNorm (for memory_emb_tpye==2 only)
encoder_type        : 1      # 1: FC encoder, 2: VAE        (for memory_emb_tpye==3 only)
use_AEM             : True   # True: proposed model(opt-propagation + memory shift), False: EMC model
flag_stats_norm     : True   # True: use normalized value for Episodic memory searching
delta_cover_type    : 1      # 1: positive 2sigma (1.6e-5), 2: +/- 3sigma (1.3e-3) (active only for fixed_delta==True)
fixed_delta         : True   # for parametric study of atol/rtol
additional_update   : True   # True: conduct additional update for EM with replay buffer data 
optimality_incentive: False  # True: applying optimality incentive (discard episodic control error)
optimality_type     : 1      # 1: expected value, 2: optimistic value

# for memory_emb_tpye==3 only
lambda_s         : 0.1     # denoted as lambda_rcon in the paper
lambda_kl        : 0.0001  # for encoder_type==2 only
#--------------------------------------------------

# Qatten coefficient
n_head: 4 # attention head number
attend_reg_coef: 0.001 # attention regulation coefficient  # For MMM2 and 3s5z_vs_3s6z, it is 0.001
state_bias: True # the constant value cs in the paper
mask_dead: False
#weighted_head: True # weighted head Q-values, for MMM2 and 3s5z_vs_3s6z, it is True
#nonlinear: True # non-linearity, for MMM2, it is True

num_circle: 1

#..MMM2 (easy and hard)
curiosity_scale: 0.0
curiosity_decay: True
curiosity_decay_rate: 0.9
curiosity_decay_cycle: 100000
curiosity_decay_stop: 0.0
epsilon_anneal_time: 50000
weighted_head: True # weighted head Q-values, for MMM2 and 3s5z_vs_3s6z, it is True
nonlinear: True # non-linearity, for MMM2, it is True

##.. 3s5z_vs_3s6z
#curiosity_scale: 0.08
#curiosity_decay: True
#curiosity_decay_rate: 0.95
#curiosity_decay_cycle: 100000
#curiosity_decay_stop: 0.01
#epsilon_anneal_time: 200000
#weighted_head: True # weighted head Q-values, for MMM2 and 3s5z_vs_3s6z, it is True
#nonlinear: False # non-linearity, for MMM2, it is True


##.. 6h_vs_8z
#curiosity_scale: 0.2
#curiosity_decay: True
#curiosity_decay_rate: 0.9
#curiosity_decay_cycle: 200000
#curiosity_decay_stop: 0.01
#epsilon_anneal_time: 50000
#weighted_head: False # weighted head Q-values, for MMM2 and 3s5z_vs_3s6z, it is True
#nonlinear: False # non-linearity, for MMM2, it is True


##.. corridor
#curiosity_scale: 0.1
#curiosity_decay: True
#curiosity_decay_rate: 0.8
#curiosity_decay_cycle: 200000
#curiosity_decay_stop: 0.01
#epsilon_anneal_time: 50000
#weighted_head: False # weighted head Q-values, for MMM2 and 3s5z_vs_3s6z, it is True
#nonlinear: False # non-linearity, for MMM2, it is True


save_buffer: False




mac: "fast_mac"
#agent: "rnn_individualQ"
#use_individual_Q: True
agent: "rnn_fast"
use_individual_Q: False
individual_q_loss_weight: 0.01

is_prioritized_buffer: False
use_emdqn: True
emdqn_loss_weight: 0.1

emdqn_buffer_size: 1000000
emdqn_latent_dim: 4

soft_update_tau: 0.005
vdn_soft_update: True
predict_vdn_target: True
predict2_vdn_target: True
use_qtotal_td: False
name: "EMU_sc2_hard"

# ————————————————————————use individual reward【不用】——————————————
rewardnet_used: False      # 使用transformer进行奖励分解 ❗️
rewardnet_weight: 0.001
rewardnet_head: 4
rewardnet_embed_size: 128
predictor_lr: 0.005
# ————————————————————————use individual curiosity——————————————
individual_curiostiy: True

# ————————————————————————time and space credit assignment————————————————————
use_credit_assignment: True
time_attention_head: 4
time_attention_embed_size: 64
ca_loss2_weight: 0.01

n_heads: 8   # 4
n_layers: 6  # 3
hidden_size: 128
reg: True    # 正则化损失
alpha: 0.7  # 正则化权重
beta: 0.7
predictor_lr_rm: 0.003
credit_scale: 0.01